version: "3.5"

services:
  app:
    image: mealmate
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis

  postgres:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Qwerty1
      - POSTGRES_DB=meal-mate
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres: