server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/meal-mate
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Qwerty1}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: 3600000
  session:
    store-type: redis
  servlet:
    session:
      timeout: 43200m
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 17276295347-iu2celou0h00348optul0f4410r2p25i.apps.googleusercontent.com
            clientSecret: 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

app:
  jwt:
    secret: ${JWT_SECRET:8ea3d739671fc877d8810dac1fdc69bb93b60ba23b287f5d767ba46373eac681}
    expiration: ${JWT_EXPIRATION:108000000}
  nutrition:
    api:
      key: 7075c6fbf1bf46edb8e0cdc8a321e523
      url: https://api.spoonacular.com